### ISSUE TITLE
An errer occurs when running docker-compose.estonia-osm.yml

### ISSUE THREAD

**Issue by DongshengChen9** [yuzzfeng/D2G2#1]
When running command "docker-compose -f docker-compose.estonia-osm.yml up postgres osm2pgsql"
Raise an error "can't read /etc/apt/sources.list  No such directory or file"
It occurs in ....../osm2pgsql/Dockerfile
Line 4: RUN sed -e s%http://archive.ubuntu.com/ubuntu/%mirror://mirrors.ubuntu.com/mirrors.txt% -i /etc/apt/sources.list

**Comment by apano-on** [comment]
Hi Dongsheng,

Thanks for spotting the issue. There was indeed a bug which had been fixed in a separate branch, but had not been merged yet ( now merged via https://github.com/yuzzfeng/D2G2/commit/89b6004611d18686b98d3b6465ef3147e844af55). The line causing the issue was redundant and has been removed. 

Also, under WP1 there is an additional demo/example utilizing Munich/Bavaria data to construct and run some queries on a VKG which integrates both CityGML and OSM data for Munich.

**Comment by DongshengChen9** [comment]
Hi Albulen, Thank you very much. I will try to deploy the new demo!
